# Winter Configuration - Password Authentication
# Copy this to ~/.winter/config.yaml and modify with your settings

account: your_account.snowflakecomputing.com
user: your_username
auth_method: password
password: null  # Always prompted for security
warehouse: COMPUTE_WH
database: YOUR_DATABASE
schema: PUBLIC
role: YOUR_ROLE
table_prefix: ""  # Optional: prefix for all table references
connection_timeout: 5  # Minutes timeout

security:
  allowed_all_query_types: false  # SELECT-only enforced
  audit_logging: true
  blocked_schemas: []
  allowed_schemas: []